sudo: false

dist: trusty

language:
  - go

go:
  - "1.12"
  - "1.13"

git:
  depth: 1

cache:
  directories:
    - $GOPATH/pkg/mod

services:
  - docker

script:
  - ./hack/presubmit.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
